ProjectIntake/Models/AccountModel.cs
using System.ComponentModel.DataAnnotations;

namespace ProjectIntake.Models
{
    public class AccountModel
    {
        private string firstName;
        private string lastName;
        private string email;
        private string organization;
        private string password;
        private int id;
        

        public AccountModel() {
            this.firstName = string.Empty;
            this.lastName = string.Empty;
            this.email = string.Empty;
            this.organization = string.Empty;
            this.password = string.Empty;
            this.id = 0;
        }


        public AccountModel(string firstName, string lastName, string email, string organization, string password, int id) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.email = email;
            this.organization = organization;
            this.password = password;
            this.id = id;
        }

        public AccountModel(string firstName, string lastName, string email, string organization, string password)
        {
            this.firstName = firstName;
            this.lastName = lastName;
            this.email = email;
            this.organization = organization;
            this.password = password;
        }

        //for logging in
        public AccountModel(string firstName, string lastName, string password)
        {
            this.firstName = firstName;
            this.lastName = lastName;
            this.password = password;
        }

        public string FirstName {
            get 
            { 
                return firstName; 
            }
            set
            {
                firstName = value;
            }
        }

        public string LastName
        {
            get
            {
                return lastName;
            }
            set
            {
                lastName = value;
            }
        }


        public string Email
        {
            get
            {
                return email;
            }
            set
            {
                email = value;
            }
        }

       
        public string Organization
        {
            get
            {
                return organization;
            }
            set
            {
                organization = value;
            }
        }

        public string Password
        {
            get
            {
                return password;
            }
            set
            {
                password = value;
            }
        }

        public int Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }

        //need to learn how to add cookie here
    }
}

ProjectIntake/Models/DashboardViewModel.cs
namespace ProjectIntake.Models
{
    public class ProjectViewModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string SubmittedBy { get; set; }

    }

    public class ProfileViewModel
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Organization { get; set; }

    }

    public class DashboardViewModel
    {
        public List<ProjectViewModel> ProjectsToReview { get; set; }
        public List<ProfileViewModel> ProfilesToReview { get; set; }
    }

}

ProjectIntake/Models/ErrorViewModel.cs
namespace ProjectIntake.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjectIntake/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectIntake.Controllers
{
    public class AccountController : Controller
    {

      
        public IActionResult CreateAccount()
        {
            return View();
        }

        public IActionResult AccountLogin()
        {
            return View();
        }
        public IActionResult ClientLogin()
        {
            return View();
        }
        public IActionResult AdminLogin()
        {
            return View();
        }
        public IActionResult ClientCreateAccount()
        {
            return View();
        }
    }
}

ProjectIntake/Controllers/ClientDashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectIntake.Controllers
{
    public class ClientDashboardController : Controller
    {
        public IActionResult ClientDashboard()
        {
            return View("~/Views/Client/Main/ClientDashboard.cshtml");

        }
    }
}

ProjectIntake/Controllers/ClientViewProjectDetailsController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectIntake.Controllers
{
    public class ClientViewProjectDetailsController : Controller
    {
        public IActionResult ClientViewProjectDetails()
        {
            return View("~/Views/Client/Project/ClientViewProjectDetails.cshtml");
        }
    }
}

ProjectIntake/Controllers/ClientViewProjectsController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectIntake.Controllers
{
    public class ClientViewProjectsController : Controller
    {
        public IActionResult ClientViewProjects()
        {
            return View("~/Views/Client/Project/ClientViewProjects.cshtml");
        }
    }
}

ProjectIntake/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectIntake.Models;

namespace ProjectIntake.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Dashboard()
        {

            return View("~/Views/Admin/Main/Dashboard.cshtml");
        }
    }
}

ProjectIntake/Controllers/EditProfileController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectIntake.Controllers
{
    public class EditProfileController : Controller
    {
        public IActionResult EditProfile()
        {
            return View("~/Views/Client/Profile/EditProfile.cshtml");
        }
    }
}

ProjectIntake/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectIntake.Models;
using System.Diagnostics;

namespace ProjectIntake.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View("~/Views/Account/AdminLogin.cshtml");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjectIntake/Controllers/LandingController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectIntake.Controllers
{
    public class LandingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ProjectIntake/Controllers/ManageProfilesController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectIntake.Controllers
{
    public class ManageProfilesController : Controller
    {
        public IActionResult ManageProfiles ()
        {
            return View("~/Views/Admin/Profile/ManageProfiles.cshtml");
        }
    }
}

ProjectIntake/Controllers/ManageProjectsController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectIntake.Controllers
{
    public class ManageProjectsController : Controller
    {
        public IActionResult ManageProjects()
        {
            return View("~/Views/Admin/Project/ManageProjects.cshtml");
        }
    }
}

ProjectIntake/Controllers/ViewProfileController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectIntake.Controllers
{
    public class ViewProfileController : Controller
    {
        public IActionResult ViewProfile()
        {
            return View("~/Views/Admin/Profile/ViewProfile.cshtml");

        }
    }
}

ProjectIntake/Controllers/ViewProjectController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectIntake.Controllers
{
    public class ViewProjectController : Controller
    {
        public IActionResult ViewProject()
        {
            return View("~/Views/Admin/Project/ViewProject.cshtml");

        }
    }
}

ProjectIntake/Views/Admin/Main/Dashboard.cshtml
@{
    Layout = null;
}
<html>
<head>
    <link href="~/css/ProjectIntake.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <nav>
        <ul>
            <li><a asp-controller="Dashboard" asp-action="Dashboard">Project Intake</a></li>
            <li><a asp-controller="Dashboard" asp-action="Dashboard">Dashboard</a></li>
            <li><a asp-controller="ManageProjects" asp-action="ManageProjects">Manage Projects</a></li>
            <li><a asp-controller="ManageProfiles" asp-action="ManageProfiles">Manage Profiles</a></li>
            <li><a asp-controller="Account" asp-action="AdminLogin">Logout</a></li>
        </ul>
    </nav>

    <div class="project-review">
        <h2 align ="center">Projects To Be Reviewed</h2>
        <table id="projects-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Submitted By</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Class Registration App</td>
                    <td>An updated way to register for disaster classes</td>
                    <td>Temple University</td>
                    <td><a class="button-link" asp-controller="ViewProject" asp-action="ViewProject">View Project</a></td>
                </tr>
                <tr>
                    <td>Food Truck App</td>
                    <td>Locating food trucks on campus through GPS</td>
                    <td>Food Truck LLC</td>
                    <td><a class="button-link" asp-controller="ViewProject" asp-action="ViewProject">View Project</a></td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="profile-review">
        <h2 align="center">Profiles</h2>
        <table id="profiles-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Organization</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Jane Doe</td>
                    <td>jane.d@example.com</td>
                    <td>JP Morgan</td>
                    <td><a class="button-link" asp-controller="ViewProfile" asp-action="ViewProfile">View Profile</a></td>
                </tr>
                <tr>
                    <td>John Smith</td>
                    <td>john.s@example.com</td>
                    <td>Intake</td>
                    <td><a class="button-link" asp-controller="ViewProfile" asp-action="ViewProfile">View Profile</a></td>
                </tr>
            </tbody>
        </table>
    </div>
    </body>
</html>

ProjectIntake/Views/Admin/Main/LandingPage.cshtml
@{
    Layout = null;
}
<html>
<head>
    <link href="~/css/ProjectIntake.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <nav>
        <ul>
            <li><a asp-controller="Dashboard" asp-action="Dashboard">Project Intake</a></li>
            <li><a asp-controller="Dashboard" asp-action="Dashboard">Dashboard</a></li>
            <li><a asp-controller="ManageProjects" asp-action="ManageProjects">Manage Projects</a></li>
            <li><a asp-controller="ManageProfiles" asp-action="ManageProfiles">Manage Profiles</a></li>
            <li><a asp-controller="Account" asp-action="AccountLogin">Logout</a></li>
        </ul>
    </nav>

    <div class="project-review">
        <h2>Projects To Be Reviewed</h2>
        <table id="projects-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Submitted By</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Class Registration App</td>
                    <td>An updated way to register for disaster classes</td>
                    <td>Temple University</td>
                    <td><a class="button-link" asp-controller="ViewProject" asp-action="ViewProject">View Project</a></td>
                </tr>
                <tr>
                    <td>Food Truck App</td>
                    <td>Locating food trucks on campus through GPS</td>
                    <td>Food Truck LLC</td>
                    <td><a class="button-link" asp-controller="ViewProject" asp-action="ViewProject">View Project</a></td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="profile-review">
        <h2>Profiles To Be Reviewed</h2>
        <table id="profiles-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Organization</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Jane Doe</td>
                    <td>jane.d@example.com</td>
                    <td>JP Morgan</td>
                    <td><a class="button-link" asp-controller="ViewProfile" asp-action="ViewProfile">View Profile</a></td>
                </tr>
                <tr>
                    <td>John Smith</td>
                    <td>john.s@example.com</td>
                    <td>Intake</td>
                    <td><a class="button-link" asp-controller="ViewProfile" asp-action="ViewProfile">View Profile</a></td>
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>

ProjectIntake/Views/Admin/Profile/ManageProfiles.cshtml
@{
    Layout = null; // This will remove the default layout to match the wireframe provided.
}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="~/css/ProjectIntake.css">
</head>
<body>
    <div id="header">
        <nav>
            <ul>
                <li><a asp-controller="Dashboard" asp-action="Dashboard">Project Intake</a></li>
                <li><a asp-controller="Dashboard" asp-action="Dashboard">Dashboard</a></li>
                <li><a asp-controller="ManageProjects" asp-action="ManageProjects">Manage Projects</a></li>
                <li><a asp-controller="ManageProfiles" asp-action="ManageProfiles">Manage Profiles</a></li>
                <li><a asp-controller="Account" asp-action="AccountLogin">Logout</a></li>
            </ul>
        </nav>
    </div>
    <div id="filter">
        <table>
            <tr>
                <td>Profile Status</td>
                <td>Organization</td>
                <td>First Name</td>
                <td>Last Name</td>
            </tr>
            <tr>
                <td>
                    <select>
                        <option value="Pending">Pending</option>
                        <option value="Under Review">Under Review</option>
                    </select>
                </td>
                <td><input type="text"></td>
                <td><input type="text"></td>
                <td><input type="text"></td>
            </tr>
        </table>
    </div>
    <div id="profile-list">
        <table>
            <thead>
                <tr>
                    <th>Profile ID</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Organization</th>
                    <th>Email</th>
                    <th>Review Status</th>
                    <th>View Profile</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Neel1234</td>
                    <td>Neel</td>
                    <td>Patel</td>
                    <td>Temple University</td>
                    <td>Neel@JP.com</td>
                    <td>Pending</td>
                    <td><a class="button-link" asp-controller="ViewProfile" asp-action="ViewProfile">View Profile</a></td>
                </tr>
                <tr>
                    <td>Nathan1234</td>
                    <td>Nathan</td>
                    <td>Marzina</td>
                    <td>Temple University</td>
                    <td>nate@Nsync.com</td>
                    <td>Approved</td>
                    <td><a class="button-link" asp-controller="ViewProfile" asp-action="ViewProfile">View Profile</a></td>
                </tr>
                <!-- Add more rows as needed -->
            </tbody>
        </table>
    </div>
</body>
</html>

ProjectIntake/Views/Admin/Profile/ViewProfile.cshtml
@{
    Layout = null; // No layout to match the wireframe
}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="~/css/ProjectIntake.css">
</head>
<body>
    <div id="header">
        <nav>
            <ul>
                <li><a asp-controller="Dashboard" asp-action="Dashboard">Project Intake</a></li>
                <li><a asp-controller="Dashboard" asp-action="Dashboard">Dashboard</a></li>
                <li><a asp-controller="ManageProjects" asp-action="ManageProjects">Manage Projects</a></li>
                <li><a asp-controller="ManageProfiles" asp-action="ManageProfiles">Manage Profiles</a></li>
                <li><a asp-controller="Account" asp-action="AccountLogin">Logout</a></li>
            </ul>
        </nav>
    </div>

    <div id="content">
        <div id="profile-info">
            <div id="profile-details">
                <h2>First Name</h2>
                <p>Neel</p>
                <h2>Last Name</h2>
                <p>Patel</p>
                <h2>Organization</h2>
                <p>NSYNC</p>
                <h2>Email</h2>
                <p>Neel@JP.com</p>
            </div>
        </div>

        <div id="profile-status">
            <table>
                <tr>
                    <th>Profile ID</th>
                    <th>Status</th>
                    <th>Created Date:</th>
                    <th>Review Date</th>
                </tr>
                <tr>
                    <td>Neel1234</td>
                    <td>
                        <select>
                            <option value="Pending" selected>Pending</option>
                            <option value="Under Review">Under Review</option>
                            <option value="Rejected">Rejected</option>
                            <option value="Approved">Approved</option>
                        </select>
                    </td>
                    <td>2/10/2024</td>
                    <td>-</td>
                </tr>
            </table>
        </div>
    </div>
</body>
</html>

ProjectIntake/Views/Admin/Project/ManageProjects.cshtml
@{
    Layout = null; // No layout to match the wireframe
}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="~/css/ProjectIntake.css">
</head>
<body>
    <div id="header">
        <nav>
            <ul>
                <li><a asp-controller="Dashboard" asp-action="Dashboard">Project Intake</a></li>
                <li><a asp-controller="Dashboard" asp-action="Dashboard">Dashboard</a></li>
                <li><a asp-controller="ManageProjects" asp-action="ManageProjects">Manage Projects</a></li>
                <li><a asp-controller="ManageProfiles" asp-action="ManageProfiles">Manage Profiles</a></li>
                <li><a asp-controller="Account" asp-action="AccountLogin">Logout</a></li>
            </ul>
        </nav>
    </div>
    <div id="content">
        <div id="filter">
            <table>
                <tr>
                    <td>Profile Status</td>
                    <td>Date</td>
                    <td>Organization</td>
                </tr>
                <tr>
                    <td>
                        <select>
                            <option value="Pending">Pending</option>
                            <option value="Under Review">Under Review</option>
                        </select>
                    </td>
                    <td><input type="text"></td>
                    <td><input type="text"></td>
                </tr>
            </table>
        </div>
        <div id="project-list">
            <table>
                <thead>
                    <tr>
                        <th>Project Name</th>
                        <th>Short Desc</th>
                        <th>Project Status</th>
                        <th>Comments</th>
                        <th>View Details</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Class Registration</td>
                        <td>Faster way to register for classes</td>
                        <td>Pending Review</td>
                        <td>None</td>
                        <td><a class="button-link" asp-controller="ViewProject" asp-action="ViewProject">View Project</a></td>
                    </tr>
                    <tr>
                        <td>Food Truck App</td>
                        <td>Ordering from food trucks on campus through grubhub</td>
                        <td>Denied</td>
                        <td>We don't like it. -Someone<br>2 Other comments</td>
                        <td><a class="button-link" asp-controller="ViewProject" asp-action="ViewProject">View Project</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

ProjectIntake/Views/Admin/Project/ViewProject.cshtml
@{
    Layout = null; // No layout to match the wireframe
}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="~/css/ProjectIntake.css">
</head>
<body>
    <div id="header">
        <nav>
            <ul>
                <li><a asp-controller="Dashboard" asp-action="Dashboard">Project Intake</a></li>
                <li><a asp-controller="Dashboard" asp-action="Dashboard">Dashboard</a></li>
                <li><a asp-controller="ManageProjects" asp-action="ManageProjects">Manage Projects</a></li>
                <li><a asp-controller="ManageProfiles" asp-action="ManageProfiles">Manage Profiles</a></li>
                <li><a asp-controller="Account" asp-action="AccountLogin">Logout</a></li>
            </ul>
        </nav>
    </div>

    <div id="content">
        <h2>Class Registration</h2>
        <div class="description">
            <strong>Description:</strong>
            <p>Crafted with precision to optimize the academic journey, the Class Registration System offers students and administrators a seamless experience through its intuitive interface, dynamic course catalog, and efficient registration management tools, ensuring hassle-free enrollment and streamlined administrative processes.</p>
        </div>
        <table>
            <tr>
                <th>Profile ID</th>
                <th>Project Status</th>
                <th>Submitted Date:</th>
                <th>Review Date</th>
            </tr>
            <tr>
                <td>Neel1234</td>
                <td>
                    <select>
                        <option value="Pending">Pending</option>
                        <option value="Under Review">Under Review</option>
                        <option value="Rejected">Rejected</option>
                        <option value="Approved">Approved</option>
                    </select>
                </td>
                <td>2/10/2024</td>
                <td>-</td>
            </tr>
        </table>
    </div>
</body>
</html>

ProjectIntake/Views/Client/Main/ClientDashboard.cshtml
@{
    Layout = null;
}
<html>
<head>
    <link href="~/css/ProjectIntake.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <nav>
        <ul>
            <li><a asp-controller="ClientDashboard" asp-action="ClientDashboard">Project Intake</a></li>
            <li><a asp-controller="ClientDashboard" asp-action="ClientDashboard">Dashboard</a></li>
            <li><a asp-controller="ClientViewProjects" asp-action="ClientViewProjects">View Submitted Projects</a></li>
            <li><a asp-controller="EditProfile" asp-action="EditProfile">Edit Profile</a></li>
            <li><a asp-controller="Account" asp-action="AccountLogin">Logout</a></li>
        </ul>
    </nav>

    <div class="project-review">
        <h2>Projects under review</h2>
        <table id="projects-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Submitted Date:</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Class Registration App</td>
                    <td>An updated way to register for disaster classes</td>
                    <td>2/20/2024</td>
                    <td><a class="button-link" asp-controller="ClientViewProjectDetails" asp-action="ClientViewProjectDetails">View Project</a></td>
                </tr>
                <tr>
                    <td>Food Truck App</td>
                    <td>Locating food trucks on campus through GPS</td>
                    <td>2/25/2024</td>
                    <td><a class="button-link" asp-controller="ClientViewProjectDetails" asp-action="ClientViewProjectDetails">View Project</a></td>
                </tr>
                <tr>
                    <td>Bathroom Finder App</td>
                    <td>Finds the nearest bathroom on campus</td>
                    <td>3/3/2024</td>
                    <td><a class="button-link" asp-controller="ClientViewProjectDetails" asp-action="ClientViewProjectDetails">View Project</a></td>
                </tr>
                <tr>
                    <td>Food Truck App</td>
                    <td>Locating food trucks on campus through GPS</td>
                    <td>3/10/2024</td>
                    <td><a class="button-link" asp-controller="ClientViewProjectDetails" asp-action="ClientViewProjectDetails">View Project</a></td>
                </tr>
            </tbody>
        </table>
        <td><a class="button-link" asp-controller="CreateProject" asp-action="CreateProject">Create Project</a></td>
    </div>
    </body>
</html>

ProjectIntake/Views/Client/Profile/EditProfile.cshtml
@{
    Layout = null; // No layout to match the wireframe
}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="~/css/ProjectIntake.css">
</head>
<body>
    <div id="header">
        <nav>
            <ul>
                <li><a asp-controller="ClientDashboard" asp-action="ClientDashboard">Project Intake</a></li>
                <li><a asp-controller="ClientDashboard" asp-action="ClientDashboard">Dashboard</a></li>
                <li><a asp-controller="ClientViewProjects" asp-action="ClientViewProjects">View Submitted Projects</a></li>
                <li><a asp-controller="EditProfile" asp-action="EditProfile">Edit Profile</a></li>
                <li><a asp-controller="Account" asp-action="AccountLogin">Logout</a></li>
            </ul>
        </nav>
    </div>

    <div id="content">
        <div id="profile-edit-form">
            <h2>Edit Profile</h2>
                <!-- Update the action attribute to your form handler endpoint -->
                <label for="firstName">First Name:</label>
                <input type="text" id="firstName" name="firstName" value="Nathan">

                <label for="lastName">Last Name:</label>
                <input type="text" id="lastName" name="lastName" value="Marzina">

                <label for="email">Email:</label>
                <input type="email" id="email" name="email" value="NJMarzina@gmail.com">

                <label for="organization">Organization:</label>
                <input type="text" id="organization" name="organization" value="Temple University">

                <input type="submit" value="Submit Changes" class="button-link">
        </div>
    </div>
</body>
</html>

ProjectIntake/Views/Client/Project/ClientViewProjects.cshtml
@{
    Layout = null; // No layout to match the wireframe
}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="~/css/ProjectIntake.css">
</head>
<body>
    <div id="header">
        <nav>
            <ul>
                <li><a asp-controller="ClientDashboard" asp-action="ClientDashboard">Project Intake</a></li>
                <li><a asp-controller="ClientDashboard" asp-action="ClientDashboard">Dashboard</a></li>
                <li><a asp-controller="ClientViewProjects" asp-action="ClientViewProjects">View Submitted Projects</a></li>
                <li><a asp-controller="EditProfile" asp-action="EditProfile">Edit Profile</a></li>
                <li><a asp-controller="Account" asp-action="AccountLogin">Logout</a></li>
            </ul>
        </nav>
    </div>
    <div id="content">
        <div id="filter">
            <table>
                <tr>
                    <td>Profile Status</td>
                    <td>Date</td>
                    <td>Organization</td>
                </tr>
                <tr>
                    <td>
                        <select>
                            <option value="Pending">Pending</option>
                            <option value="Under Review">Under Review</option>
                        </select>
                    </td>
                    <td><input type="text"></td>
                    <td><input type="text"></td>
                </tr>
            </table>
        </div>
        <div id="project-list">
            <table>
                <thead>
                    <tr>
                        <th>Project Name</th>
                        <th>Short Desc</th>
                        <th>Project Status</th>
                        <th>Comments</th>
                        <th>View Details</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Class Registration</td>
                        <td>Faster way to register for classes</td>
                        <td>Pending Review</td>
                        <td>None</td>
                        <td><a class="button-link" asp-controller="ClientViewProjectDetails" asp-action="ClientViewProjectDetails">View Project</a></td>
                    </tr>
                    <tr>
                        <td>Food Truck App</td>
                        <td>Ordering from food trucks on campus through grubhub</td>
                        <td>Denied</td>
                        <td>We don't like it. -Someone<br>2 Other comments</td>
                        <td><a class="button-link" asp-controller="ClientViewProjectDetails" asp-action="ClientViewProjectDetails">View Project</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>